services:
  - type: web
    name: be-todo
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02230299.onrender.com
